// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVO7WvQG9nGZbWhiDNNxzPNzj2D9XiI8k',
    appId: '1:70846535935:web:27a881478929ac66f714ca',
    messagingSenderId: '70846535935',
    projectId: 'project-d9ff8',
    authDomain: 'project-d9ff8.firebaseapp.com',
    databaseURL: 'https://project-d9ff8-default-rtdb.firebaseio.com',
    storageBucket: 'project-d9ff8.firebasestorage.app',
    measurementId: 'G-G7GGL5N7RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn_aXBS43xp5ULt_So8HmoNOT1ifjp2LA',
    appId: '1:70846535935:android:1a138332d1a75b35f714ca',
    messagingSenderId: '70846535935',
    projectId: 'project-d9ff8',
    databaseURL: 'https://project-d9ff8-default-rtdb.firebaseio.com',
    storageBucket: 'project-d9ff8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUvlWzv4IMUHXTjIF2ryVPd_mjw_pPYZI',
    appId: '1:70846535935:ios:a9bd8c9660b09e08f714ca',
    messagingSenderId: '70846535935',
    projectId: 'project-d9ff8',
    databaseURL: 'https://project-d9ff8-default-rtdb.firebaseio.com',
    storageBucket: 'project-d9ff8.firebasestorage.app',
    androidClientId: '70846535935-965rn25nuiaaqsfbhmn0o769c9juv8na.apps.googleusercontent.com',
    iosClientId: '70846535935-saheku3bcholmumktbu5ahp9uislvjd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication33',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUvlWzv4IMUHXTjIF2ryVPd_mjw_pPYZI',
    appId: '1:70846535935:ios:a9bd8c9660b09e08f714ca',
    messagingSenderId: '70846535935',
    projectId: 'project-d9ff8',
    databaseURL: 'https://project-d9ff8-default-rtdb.firebaseio.com',
    storageBucket: 'project-d9ff8.firebasestorage.app',
    androidClientId: '70846535935-965rn25nuiaaqsfbhmn0o769c9juv8na.apps.googleusercontent.com',
    iosClientId: '70846535935-saheku3bcholmumktbu5ahp9uislvjd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication33',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVO7WvQG9nGZbWhiDNNxzPNzj2D9XiI8k',
    appId: '1:70846535935:web:537b528e004594b2f714ca',
    messagingSenderId: '70846535935',
    projectId: 'project-d9ff8',
    authDomain: 'project-d9ff8.firebaseapp.com',
    databaseURL: 'https://project-d9ff8-default-rtdb.firebaseio.com',
    storageBucket: 'project-d9ff8.firebasestorage.app',
    measurementId: 'G-JJBWSZNRR2',
  );

}